/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Go Backend API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod'

export const HealthGetHealth200 = zod.object({
  status: zod.string().optional(),
  version: zod.string().optional(),
})

export type HealthGetHealth200 = zod.input<typeof HealthGetHealth200>
export type HealthGetHealth200Output = zod.output<typeof HealthGetHealth200>
