/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Go Backend API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod'

export const UsersGetUser200 = zod.object({
  createdAt: zod.string().optional(),
  displayName: zod.string().optional(),
  email: zod.string().optional(),
  id: zod.string().optional(),
  updatedAt: zod.string().optional(),
})

export type UsersGetUser200 = zod.input<typeof UsersGetUser200>
export type UsersGetUser200Output = zod.output<typeof UsersGetUser200>
