/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Go Backend API
 * OpenAPI spec version: v1
 */
import { useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import { HealthGetHealth200, UsersGetUser200 } from './models'

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

export type healthGetHealthResponse200 = {
  data: HealthGetHealth200
  status: 200
}

export type healthGetHealthResponseSuccess = healthGetHealthResponse200 & {
  headers: Headers
}
export type healthGetHealthResponse = healthGetHealthResponseSuccess

export const getHealthGetHealthUrl = () => {
  return `${import.meta.env.VITE_API_BASE_URL}/api/v1/health`
}

/**
 * @summary GetHealth
 */
export const healthGetHealth = async (
  options?: RequestInit,
): Promise<healthGetHealthResponse> => {
  const res = await fetch(getHealthGetHealthUrl(), {
    ...options,
    method: 'GET',
  })

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase()
  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const parsedBody = body
    ? contentType.includes('json')
      ? JSON.parse(body)
      : body
    : {}
  const data = contentType.includes('json')
    ? HealthGetHealth200.parse(parsedBody)
    : parsedBody
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as healthGetHealthResponse
}

export const getHealthGetHealthQueryKey = () => {
  return [`${import.meta.env.VITE_API_BASE_URL}/api/v1/health`] as const
}

export const getHealthGetHealthQueryOptions = <
  TData = Awaited<ReturnType<typeof healthGetHealth>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>
  >
  fetch?: RequestInit
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getHealthGetHealthQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthGetHealth>>> = ({
    signal,
  }) => healthGetHealth({ signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthGetHealth>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthGetHealthQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthGetHealth>>
>
export type HealthGetHealthQueryError = unknown

export function useHealthGetHealth<
  TData = Awaited<ReturnType<typeof healthGetHealth>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthGetHealth>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthGetHealth>>,
          TError,
          Awaited<ReturnType<typeof healthGetHealth>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useHealthGetHealth<
  TData = Awaited<ReturnType<typeof healthGetHealth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthGetHealth>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthGetHealth>>,
          TError,
          Awaited<ReturnType<typeof healthGetHealth>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useHealthGetHealth<
  TData = Awaited<ReturnType<typeof healthGetHealth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthGetHealth>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary GetHealth
 */

export function useHealthGetHealth<
  TData = Awaited<ReturnType<typeof healthGetHealth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthGetHealth>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getHealthGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}

export type usersGetUserResponse200 = {
  data: UsersGetUser200
  status: 200
}

export type usersGetUserResponseSuccess = usersGetUserResponse200 & {
  headers: Headers
}
export type usersGetUserResponse = usersGetUserResponseSuccess

export const getUsersGetUserUrl = (id: string) => {
  return `${import.meta.env.VITE_API_BASE_URL}/api/v1/users/${id}`
}

/**
 * @summary GetUser
 */
export const usersGetUser = async (
  id: string,
  options?: RequestInit,
): Promise<usersGetUserResponse> => {
  const res = await fetch(getUsersGetUserUrl(id), {
    ...options,
    method: 'GET',
  })

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase()
  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const parsedBody = body
    ? contentType.includes('json')
      ? JSON.parse(body)
      : body
    : {}
  const data = contentType.includes('json')
    ? UsersGetUser200.parse(parsedBody)
    : parsedBody
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as usersGetUserResponse
}

export const getUsersGetUserQueryKey = (id: string) => {
  return [`${import.meta.env.VITE_API_BASE_URL}/api/v1/users/${id}`] as const
}

export const getUsersGetUserQueryOptions = <
  TData = Awaited<ReturnType<typeof usersGetUser>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersGetUser>>, TError, TData>
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getUsersGetUserQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersGetUser>>> = ({
    signal,
  }) => usersGetUser(id, { signal, ...fetchOptions })

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof usersGetUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersGetUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersGetUser>>
>
export type UsersGetUserQueryError = unknown

export function useUsersGetUser<
  TData = Awaited<ReturnType<typeof usersGetUser>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersGetUser>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersGetUser>>,
          TError,
          Awaited<ReturnType<typeof usersGetUser>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useUsersGetUser<
  TData = Awaited<ReturnType<typeof usersGetUser>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersGetUser>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersGetUser>>,
          TError,
          Awaited<ReturnType<typeof usersGetUser>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useUsersGetUser<
  TData = Awaited<ReturnType<typeof usersGetUser>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersGetUser>>, TError, TData>
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary GetUser
 */

export function useUsersGetUser<
  TData = Awaited<ReturnType<typeof usersGetUser>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersGetUser>>, TError, TData>
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getUsersGetUserQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}
