import 'package:flutter/material.dart';
import 'package:mobileapp/core/theme/app_color.dart';

abstract class AppColorScheme {
  static final light = ColorScheme.fromSeed(
    seedColor: AppPrimitives.blue500,
    brightness: Brightness.light,
    primary: AppPrimitives.blue500,
    onPrimary: AppPrimitives.white1000,
    primaryContainer: AppPrimitives.blue50,
    onPrimaryContainer: AppPrimitives.blue900,
    secondary: AppPrimitives.gray600,
    onSecondary: AppPrimitives.white1000,
    secondaryContainer: AppPrimitives.gray100,
    onSecondaryContainer: AppPrimitives.gray900,
    tertiary: AppPrimitives.cyan500,
    onTertiary: AppPrimitives.white1000,
    tertiaryContainer: AppPrimitives.cyan50,
    onTertiaryContainer: AppPrimitives.cyan900,
    error: AppPrimitives.red500,
    onError: AppPrimitives.white1000,
    errorContainer: AppPrimitives.red50,
    onErrorContainer: AppPrimitives.red900,
    surface: AppPrimitives.white1000,
    onSurface: AppPrimitives.gray900,
    onSurfaceVariant: AppPrimitives.gray600,
    outline: AppPrimitives.gray200,
    outlineVariant: AppPrimitives.gray100,
    shadow: AppPrimitives.black1000,
    scrim: AppPrimitives.blackAlpha60,
    inverseSurface: AppPrimitives.gray900,
    onInverseSurface: AppPrimitives.white1000,
    inversePrimary: AppPrimitives.blue300,
    surfaceTint: Colors.transparent,
  );

  static final dark = ColorScheme.fromSeed(
    seedColor: AppPrimitives.blue500,
    brightness: Brightness.dark,
    primary: AppPrimitives.blue500,
    onPrimary: AppPrimitives.white1000,
    primaryContainer: AppPrimitives.blue900,
    onPrimaryContainer: AppPrimitives.blue100,
    secondary: AppPrimitives.gray300,
    onSecondary: AppPrimitives.gray900,
    secondaryContainer: AppPrimitives.gray800,
    onSecondaryContainer: AppPrimitives.gray100,
    tertiary: AppPrimitives.cyan400,
    onTertiary: AppPrimitives.gray900,
    tertiaryContainer: AppPrimitives.cyan900,
    onTertiaryContainer: AppPrimitives.cyan100,
    error: AppPrimitives.red500,
    onError: AppPrimitives.white1000,
    errorContainer: AppPrimitives.red900,
    onErrorContainer: AppPrimitives.red100,
    surface: AppPrimitives.gray900,
    onSurface: AppPrimitives.white1000,
    onSurfaceVariant: AppPrimitives.gray400,
    outline: AppPrimitives.gray700,
    outlineVariant: AppPrimitives.gray800,
    shadow: AppPrimitives.black1000,
    scrim: AppPrimitives.blackAlpha60,
    inverseSurface: AppPrimitives.white1000,
    onInverseSurface: AppPrimitives.gray900,
    inversePrimary: AppPrimitives.blue600,
    surfaceTint: Colors.transparent,
  );
}
