// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type APIError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type EmptyResp struct {
	Success bool   `json:"success"`
	Data    string `json:"data,optional"`
}

type ErrorResp struct {
	Success bool     `json:"success"`
	Error   APIError `json:"error"`
}

type GetUserReq struct {
	ID string `path:"id"`
}

type HealthResp struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

type PaginationMeta struct {
	Page       int `json:"page"`
	PageSize   int `json:"pageSize"`
	Total      int `json:"total"`
	TotalPages int `json:"totalPages"`
}

type UserResp struct {
	ID          string `json:"id"`
	Email       string `json:"email"`
	DisplayName string `json:"displayName"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}
